#include <array>
#include <iostream>
#include <fstream>
#include <string_view>
#include <span>
#include <ranges>
#include <vector>
#include <filesystem>
#include <sstream>

constexpr std::string_view VERSION{ "1.0.0" };

void DefineAST(std::string_view output_path, std::string_view base_name,
	std::span<const std::string_view> members);

int main(int argc, char** argv)
{
	const char* path;
	if (argc != 2)
		path = "C:/Users/Eduard/Desktop/my_int/ast/";
	else
		path = argv[1];
	DefineAST(path, "Expr", { {
		"Binary   :Expr-left,Token-op,Expr-right",
		"Grouping :Expr-expression",
		"Literal  :LiteralT-value",
		"Unary    :Token-op,Expr-right"
		} } );
	return 0;
}

void DefineType(std::ostream& file, std::string_view base_name,
	std::string_view struct_name, std::string_view fiends);
void DefineVisitor(std::ofstream& file, std::span<std::string_view> types);
void ForwardDeclareTypes(std::ofstream& file, std::span<std::string_view> types);

void DefineAST(std::string_view output_path, std::string_view base_name,
	std::span<const std::string_view> members)
{
	auto path = std::string(output_path);
	std::filesystem::create_directories(path);
	path += "ast.ixx";
	std::ofstream file{ path };
	if (!file.is_open())
	{
		std::cerr << "can`t open file: " << path << std::endl;
		return;
	}
	file << "//This file was generated by ast_builder.exe v" << VERSION << '\n';
	file << "export module ast;\n\n";
	file << "import <any>;\n";
	file << "import <memory>;\n\n";
	file << "import core;\n\n";
	file << "export namespace ast\n";
	file << "{\n";
	std::vector<std::string_view> types;
	std::stringstream ss;
	constexpr std::string_view delim{ ":" };
	for (const auto& node : members)
	{
		std::vector<std::string_view> views;
		for (const auto& view : std::views::split(node, delim))
		{
			if (views.empty())
				types.emplace_back(view);
			views.emplace_back(view);
		}
			
		if (views.size() == 2)
			DefineType(ss, base_name, views[0], views[1]);
	}
	ForwardDeclareTypes(file, types);
	DefineVisitor(file, types);
	file << "struct " << base_name
		<< "\n{\n"
		<< "\tvirtual ~" << base_name << "() = default;\n"
		<< "\tvirtual std::any Accept(Visitor& visitor) = 0;\n"
		<< "};\n";
	file << ss.str();
	file << "}//namespace ast\n";
}

void ForwardDeclareTypes(std::ofstream& file, std::span<std::string_view> types)
{
	for (const auto& type : types)
		file << "struct " << type << ";\n";
	file << '\n';
}

void DefineVisitor(std::ofstream& file, std::span<std::string_view> types)
{
	file << "struct Visitor\n"
		<< "{\n"
		<< "\tvirtual ~Visitor() = default;\n";
	for (const auto& type : types)
	{
		file << "\tvirtual std::any Visit(const " << type << "& val) = 0;\n";
	}
	file << "};\n";
}

void DefineType(std::ostream& file, std::string_view base_name,
	std::string_view struct_name, std::string_view fiends)
{
	file << "struct " << struct_name << " : " << base_name << '\n'
		<< "{\n";
	std::stringstream constructor_params;
	constructor_params << "\texplicit " << struct_name << "(";
	const char* sep = "";
	std::stringstream constructor_init_list;
	constructor_init_list << "\t\t: ";
	const char* tabs2 = "";
	for (const auto& field :
		std::views::split(fiends, std::string_view(",")))
	{
		std::vector<std::string_view> type_then_name;
		for (const auto& val :
			std::views::split(
				std::string_view(field.begin(), field.end()), std::string_view("-")))
		{
			type_then_name.emplace_back(val);
		}
		if (type_then_name.size() != 2)
			continue;
		std::stringstream ss;
		if (type_then_name[0] == base_name)
		{
			ss << '\t' << "std::unique_ptr<" << type_then_name[0]
				<< "> " << type_then_name[1] << ";\n";
		}
		else
		{
			ss << '\t' << type_then_name[0] << " " << type_then_name[1] << ";\n";
		}
		file << ss.str();
		auto str = ss.str();
		str.erase(0, 1); // \t
		str.pop_back(); // \n
		str.pop_back(); // \;
		str.push_back('_');
		constructor_params << sep << str;
		constructor_init_list << tabs2 << sep << type_then_name[1] << "(std::move("
			<< std::string(type_then_name[1]) + "_))\n";
		tabs2 = "\t\t";
		sep = ", ";
	}
	constructor_params << ")\n";
	file << constructor_params.str();
	file << constructor_init_list.str()
		<< "\t\t{}\n";
	file << "\tstd::any Accept(Visitor& visitor) override\n"
		<< "\t{\n"
		<< "\t\treturn visitor.Visit(*this);\n"
		<< "\t}\n";
	file << "};\n";
}
